### ISSUE TITLE
Integrate drivers for make_ics/make_lbcs: Part II

### ISSUE THREAD

**Issue by christinaholtNOAA** [ufs-community/uw-team#1]
# AC

- [ ] PR merged into our branch
- [ ] Replaces the logic and calls to executable in run scripts with a calls to the uwtools CLI
- [ ] Moves necessary logic in run script to the configuration layer.
- [ ] Passes fundamental WE2E test suite.

# Description

These two separate scripts in SRW are nearly identical except for the configuration of chgres_cube. Let's replace both SRW scripts with a single run script that handles both types of tasks.

**Comment by WeirAE** [comment]
Completed by PR [#266](https://github.com/NOAA-GSL/ufs-srweather-app/pull/266)
